# Generated by Django 2.1.5 on 2019-01-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddClientsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_designation', models.CharField(max_length=100)),
                ('client_job_location', models.CharField(max_length=100)),
                ('client_phone_num', models.CharField(max_length=10)),
            ],
        ),
    ]
