# Generated by Django 2.1.5 on 2019-01-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjp_app', '0002_auto_20190119_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addclientsmodel',
            name='client_phone_num',
            field=models.CharField(max_length=100),
        ),
    ]
