# Generated by Django 2.1.5 on 2019-01-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjp_app', '0003_auto_20190119_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addclientsmodel',
            name='client_phone_num',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
